version: '3.5' 

services: 
    front:  
      image: frontend
      build: .
      container_name: frontend
      ports: 
        - 8080:5000
    back:
      image: backend
      build: 
          context: ../example-backend/
      container_name: backend
      ports: 
        - 5000:8080
      environment:
        - REDIS_HOST=redis
        - POSTGRES_HOST=db
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DATABASE=postgres
    db:
      image: postgres:13.2-alpine
      restart: unless-stopped
      environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DATABASE=postgres
        - POSTGRES_USER=postgres
        - PGDATA=/database
      volumes:
        - ./database:/database
    redmine:
      image: redmine:4.1-alpine
      environment:
        - REDMINE_DB_POSTGRES=db
        - REDMINE_DB_PASSWORD=postgres
      depends_on:
        - db
      ports:
        - 9999:3000
    adminer:
      image: adminer:4
      restart: always
      environment:
          - ADMINER_DESIGN=galkaev
      ports:
          - 8083:8080
    redis:
      image: redis
      container_name: redis
      command: redis-server --appendonly yes 
