version: '3.5' 

services: 
    logger:  
      image: devopsdockeruh/simple-web-service
      build: .
      volumes: 
        - C:\codeProjects\docker\own1\text.log:/usr/src/app/text.log
      container_name: logger